// File generated by FlutterFire CLI.
// ─── PLACEHOLDER ─────────────────────────────────────────────────────────────
// Replace this file with the real one generated by:
//   flutterfire configure
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android; // fallback
      case TargetPlatform.linux:
        return android; // fallback
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── REPLACE THESE WITH YOUR ACTUAL FIREBASE CONFIG ─────────────────────
  // Run: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'money-tracker-placeholder',
    storageBucket: 'money-tracker-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'money-tracker-placeholder',
    storageBucket: 'money-tracker-placeholder.appspot.com',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'money-tracker-placeholder',
    storageBucket: 'money-tracker-placeholder.appspot.com',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR-API-KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'money-tracker-placeholder',
    storageBucket: 'money-tracker-placeholder.appspot.com',
    authDomain: 'money-tracker-placeholder.firebaseapp.com',
  );
}
